
#name: Deploy to Play Store
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  build-release:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Download dependencies
#        run: npm install
#      - name: Make Gradlew Executable
#        run: cd android && chmod +x ./gradlew
#      - name: Generate Release AAB
#        run: cd android && ./gradlew bundleRelease
#      - name: Sign AAB
#        uses: r0adkll/sign-android-release@v1
#        id: sign_app
#        with:
#          releaseDirectory: android/app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#      - name: upload app-release.aab
#        uses: actions/upload-artifact@master
#        with:
#          name: app-release.aab
#          path: ${{steps.sign_app.outputs.signedReleaseFile}}
#
#  deploy-play-store:
#    needs: [build-release]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/download-artifact@master
#        with:
#          name: app-release.aab
#      - name: Publish to Play Store internal test track
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
#          packageName: com.test.test.awesomeproject
#          releaseFile: app-release.aab
#          track: internal
#          status: completed
#